### ISSUE TITLE
Multiple signature default configuration

### ISSUE THREAD

**Issue by louisboulagnon** [GregoireHebert/docusign-bundle#108]
**Describe the bug**
When several signature zones are defined in the config, only the first one is extracted in the DocusignBundle\DependencyInjection\Configuration.php

**To Reproduce**
Install and configuret the bundle, setting 2 signature zones

**Expected behavior**
See all configured signatures in the processed configuration

**Screenshots**
![Screenshot from 2021-02-14 13-27-14](https://user-images.githubusercontent.com/46677365/107876941-70824700-6ec9-11eb-9b5c-30edaf296fd2.png)

**Additional context**
I am by no means a configuration expert, so I am not sure how and what the change could impact and that's why I prefer posting an issue rather than a pull request directly, but I'm guessing there is something to fix in the Configuration.php file, around the line 121:123.
A fix I found was simply changing the line 121 from:
`->then(static function ($v) { return ['default' => [$v[0]]]; })` to `->then(static function ($v) { return ['default' => $v]; })`

**Comment by louisboulagnon** [comment]
I also discovered that configuring the docusign.yaml differently works without changing the code
```
    signatures:
        # this is an array of positions, you can have multiple signatures locations per pages
        default:
            -
                page: 1 # Default
                x_position: 200 # Top left corner in pixels
                y_position: 400 # Top left corner in pixels
            -
                page: 2 # Default
                x_position: 200 # Top left corner in pixels
                y_position: 400 # Top left corner in pixels
```
