### ISSUE TITLE
V5 roadmap

### ISSUE THREAD

**Issue by GregoireHebert** [GregoireHebert/docusign-bundle#19]
To handle multiple type of signature per file handled We need mostly to change the configuration. This is the configuration we should aim for.

## Single signature definition

Example with a click signature

```yaml
docusign:
      mode: click # mode used to sign
      demo: %kernel.debug% # default value: false. when kernel.debug is true then the api_uri is forced to `https://demo.docusign.net/restapi`
      auth_click:
          integration_id: "YourIntegrationId"
          wrap_id: "YourWrapId" # create a wrap https://support.docusign.com/en/guides/click-user-guide
      account_id: "yourAccountId"
      default_signer_name: "Grégoire Hébert"
      default_signer_email: "gregoire@les-tilleuls.coop"
      api_uri: "https://www.docusign.net/restapi"
```

## Multiple signatures definition

Example with a remote and embedded signature

```yaml
docusign:
    my_remote_signature: # Name of the signature configuration
        mode: remote # Mode used to sign
        demo: %kernel.debug%  # Default value: false

        auth_jwt:
            private_key: "YourPrivateKey"
            integration_id: "YourIntegrationId"
            user_guid: "YourUserId"

        # No account_id required for remote mode

        default_signer_name: "Grégoire Hébert" # Name of the person that will be notified and will sign the document if none is sent to the url.
        default_signer_email: "gregoire@les-tilleuls.coop" # Mail of the person that will be notified and will sign the document if none is sent to the url.

        api_uri: "https://www.docusign.net/restapi" # Docusign api uri

        callback_route_name: "docusign_callback" # Your route where to redirect the user after signature

        # To sign you need to generate a route to call.
        # The route name will be formated `docusign.sign.{signaturename}` for this one it will be `docusign.sign.my_embedded_signature` and will have `my_embedded_signature` as attribute type
        # By defining this, you have a full control over the security applied to this route. see https://symfony.com/doc/current/security/access_control.html
        sign_path: '/my/embedded/sign/path'

        signatures_overridable: false # When set to true, you can define the pages and positions through the url as query parameters.

        # Where to position the signature
        signatures:
            # this is an array of positions, you can have multiple signatures locations per document and pages
            -
                page: 1 # Default
                x_position: 200 # Top left corner in pixels
                y_position: 400 # Top left corner in pixels

        # Define the storage to use to get the file to sign
        storage: 'docusign.storage' # if you set a string, it will look for an already defined storage. It could be defined with league/flysystem-bundle or by another signature definition when the storage key is an array of values
        # when the storage key is an array it will declare a new storage as if it was using the league/flysystem-bundle it's name will be `docusign.storage.my_remote_signature`
        # Do not use this format you do have `league/flysystem-bundle` installed, use the bundle configuration.
        storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'

    my_embedded_signature:
        mode: embedded
        demo: %kernel.debug%
        auth_authorization_code:
            integration_id: "YourIntegrationId"
            user_guid: "YourUserId"

        account_id: "yourAccountId"
        default_signer_name: "Grégoire Hébert"
        default_signer_email: "gregoire@les-tilleuls.coop"

        api_uri: "https://www.docusign.net/restapi" # default

        callback_route_name: "docusign_callback"
        sign_path: '/my/embedded/sign/path/{document_type}'

        signatures_overridable: false # default

        # Where to position the signatures
        signatures:
            # Here you can use the same signature definition but sometime you have some variations in your document, by setting a name you can inject the document_type as a query parameter to select the positions.
            document_type:
                -
                    page: 1 # default
                    x_position: 200 # top left corner in pixels
                    y_position: 400 # top left corner in pixels
            document_type_variation:
                -
                    page: 1 # default
                    x_position: 200 # top left corner in pixels
                    y_position: 400 # top left corner in pixels

        # league/flysystem-bundle storage usage
        storage: 'docusign.storage'

        # Storage declared by a previous signature definition
        storage: 'docusign.storage.my_remote_signature'

        # storage declared for this signature when not using league/flysystem-bundle
        storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
```
