### ISSUE TITLE
[Help] Change Signer Name and Email

### ISSUE THREAD

**Issue by gaet592010** [GregoireHebert/docusign-bundle#97]
Hi !

I would like to change the default Signer Name / Email.

What's the best way to do this ? 
On PreSign ?

My goal is to have only One signer for the document
Thanks for you reply

**Comment by vincentchalamon** [comment]
Hi @gaet592010,

You can easily configure the default signer name and email in the bundle configuration. You will find everything you need about it from [the documentation](https://github.com/GregoireHebert/docusign-bundle/blob/v5/doc/configure-the-bundle.md).

**Comment by gaet592010** [comment]
hi @vincentchalamon 
Thanks for the doc but .

How can i sent the signer name in the url ? What URL ?

**Comment by vincentchalamon** [comment]
This bundle does not allow to set the signer properties from the url, you must use the bundle configuration. But you can use the [multiple signature configuration](https://github.com/GregoireHebert/docusign-bundle/blob/v5/doc/configure-the-bundle.md#multiple-signature-configuration) and specify in the url which configuration to use:
```yaml
# config/packages/docusign.yml
docusign:
    default:
        default_signer_name: "John DOE"
        default_signer_email: "john.doe@example.com"
        # ...

    alternative:
        default_signer_name: "Chuck NORRIS"
        default_signer_email: "chuck.norris@example.com"
        # ...
```
```twig
{# Resources/views/pouet.html.twig #}
<a href="{{ path('docusign_sign_default', {'path': document_to_sign}) }}">Use "default" configuration</a>
<a href="{{ path('docusign_sign_alternative', {'path': document_to_sign}) }}">Use "alternative" configuration</a>
```

I also recommend you to have a look at the [TestBundle](https://github.com/GregoireHebert/docusign-bundle/tree/v5/features/TestBundle) in the tests, which provides full dynamic examples of the implementation of this bundle.
